dist: trusty
sudo: false
language: node_js
node_js:
  - "8"
  - "10"

cache:
  yarn: true

before_install:
  - node --version
  - yarn --version
  - nvm --version
  - firefox --version

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm test

git:
  depth: 5
