environment:
  matrix:
    - nodejs_version: "10"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - node --version
  - yarn --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: false

cache:

clone_depth: 5
